"""Charity directory data for the 'Where to Give Your Zakat' page."""

CHARITIES = [
    # --- CANADA ---
    {
        "id": "islamic-relief-canada",
        "name": "Islamic Relief Canada",
        "country": "CA",
        "description": "International humanitarian relief with local programs across Canada. One of the largest Muslim charities operating in the country.",
        "registration_number": "BN 821565688RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.islamicreliefcanada.org",
        "donate_url": "https://www.islamicreliefcanada.org",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "human-concern-international",
        "name": "Human Concern International",
        "country": "CA",
        "description": "International development and humanitarian relief. Based in Ottawa, Canada.",
        "registration_number": "BN 119219476RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.humanconcern.org",
        "donate_url": "https://www.humanconcern.org",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "idrf",
        "name": "International Development & Relief Foundation (IDRF)",
        "country": "CA",
        "description": "Development, relief, and local programs in Canada and internationally.",
        "registration_number": "BN 141815933RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.idrf.ca",
        "donate_url": "https://www.idrf.ca",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "nzf-canada",
        "name": "National Zakat Foundation Canada",
        "country": "CA",
        "description": "Dedicated to collecting and distributing Zakat locally to Muslims in Canada who are eligible recipients.",
        "registration_number": "BN 794660050RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.nzfcanada.com",
        "donate_url": "https://www.nzfcanada.com",
        "tags": ["Local Distribution"],
        "featured": False,
    },
    {
        "id": "canada-zakat",
        "name": "Canada Zakat (DawaNet)",
        "country": "CA",
        "description": "Local Zakat collection and distribution program under DawaNet, serving Canadian Muslim communities.",
        "registration_number": "BN 762916476RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.canadazakat.org",
        "donate_url": "https://www.canadazakat.org",
        "tags": ["Local Distribution"],
        "featured": False,
    },
    {
        "id": "icna-relief-canada",
        "name": "ICNA Relief Canada",
        "country": "CA",
        "description": "Social services and humanitarian relief, including food banks, refugee resettlement, and international programs.",
        "registration_number": "BN 836468698RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.icnareliefcanada.ca",
        "donate_url": "https://www.icnareliefcanada.ca",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "penny-appeal-canada",
        "name": "Penny Appeal Canada",
        "country": "CA",
        "description": "International humanitarian aid focused on poverty alleviation, emergency relief, and sustainable development.",
        "registration_number": "BN 812040996RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.pennyappeal.ca",
        "donate_url": "https://www.pennyappeal.ca",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "mac-foundation",
        "name": "Muslim Association of Canada (MAC) Foundation",
        "country": "CA",
        "description": "Community development, education support, and local outreach programs for Canadian Muslims.",
        "registration_number": "BN 897913344RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.macfoundation.ca",
        "donate_url": "https://www.macfoundation.ca",
        "tags": ["Local Distribution"],
        "featured": False,
    },
    # --- USA ---
    {
        "id": "islamic-relief-usa",
        "name": "Islamic Relief USA",
        "country": "US",
        "description": "One of the largest Muslim humanitarian organizations in the USA, providing international emergency relief and local programs.",
        "registration_number": "EIN 95-4453134",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.irusa.org",
        "donate_url": "https://www.irusa.org",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "zakat-foundation",
        "name": "Zakat Foundation of America",
        "country": "US",
        "description": "Emergency relief, education, and orphan sponsorship worldwide. Accepts and distributes Zakat in the USA and internationally.",
        "registration_number": "EIN 36-4476244",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.zakat.org",
        "donate_url": "https://www.zakat.org",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "hhrd",
        "name": "Helping Hand for Relief & Development (HHRD)",
        "country": "US",
        "description": "Disaster relief and sustainable development programs in over 30 countries.",
        "registration_number": "EIN 36-4582186",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.hhrd.org",
        "donate_url": "https://www.hhrd.org",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "icna-relief-usa",
        "name": "ICNA Relief USA",
        "country": "US",
        "description": "Domestic social services including food pantries, disaster relief, and refugee assistance, plus international programs.",
        "registration_number": "EIN 11-3231048",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.icnarelief.org",
        "donate_url": "https://www.icnarelief.org",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "united-muslim-relief",
        "name": "United Muslim Relief (UMR)",
        "country": "US",
        "description": "International humanitarian aid responding to crises and supporting long-term development.",
        "registration_number": "EIN 20-0800422",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.unitedmuslimrelief.org",
        "donate_url": "https://www.unitedmuslimrelief.org",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "penny-appeal-usa",
        "name": "Penny Appeal USA",
        "country": "US",
        "description": "Humanitarian aid focused on water, food, education, and emergency relief.",
        "registration_number": "EIN 47-3929655",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.pennyappealusa.org",
        "donate_url": "https://www.pennyappealusa.org",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "muslim-aid-usa",
        "name": "Muslim Aid USA",
        "country": "US",
        "description": "International relief and development, focusing on emergency response and long-term aid.",
        "registration_number": "EIN 82-2169123",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.muslimaidusa.org",
        "donate_url": "https://www.muslimaidusa.org",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "embracing",
        "name": "Embracing",
        "country": "US",
        "description": "Mental health counseling and social services for Muslim communities across the USA. Focuses entirely on local needs.",
        "registration_number": None,
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.embracing.org",
        "donate_url": "https://www.embracing.org",
        "tags": ["Local Distribution"],
        "featured": False,
    },
]

COUNTRY_OPTIONS = [
    {"code": "CA", "label": "Canada", "flag": "\U0001f1e8\U0001f1e6"},
    {"code": "US", "label": "USA",    "flag": "\U0001f1fa\U0001f1f8"},
]
