"""Charity directory data for the 'Where to Give Your Zakat' page."""

# ISO 3166-1 alpha-2 → display name (countries we have charity data for)
_COUNTRY_NAMES = {
    "AU": "Australia",
    "BD": "Bangladesh",
    "CA": "Canada",
    "DE": "Germany",
    "FR": "France",
    "GB": "United Kingdom",
    "IE": "Ireland",
    "IN": "India",
    "MY": "Malaysia",
    "NL": "Netherlands",
    "NO": "Norway",
    "NZ": "New Zealand",
    "PK": "Pakistan",
    "SE": "Sweden",
    "TR": "Turkey",
    "US": "USA",
    "ZA": "South Africa",
}

# Preferred display order for country tabs
_COUNTRY_ORDER = ["CA", "US", "GB", "AU", "ZA", "DE", "FR", "NL", "IE", "SE", "NO", "NZ", "MY", "BD", "PK", "IN", "TR"]


def _flag(code: str) -> str:
    """Build a flag emoji from a 2-letter ISO country code."""
    return "".join(chr(0x1F1E6 + ord(c) - ord("A")) for c in code.upper())


CHARITIES = [
    # ── CANADA ──────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-canada",
        "name": "Islamic Relief Canada",
        "country": "CA",
        "description": "International humanitarian relief with local programs across Canada. One of the largest Muslim charities operating in the country.",
        "registration_number": "BN 821565688RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.islamicreliefcanada.org",
        "donate_url": "https://www.islamicreliefcanada.org",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "human-concern-international",
        "name": "Human Concern International",
        "country": "CA",
        "description": "International development and humanitarian relief. Based in Ottawa, Canada.",
        "registration_number": "BN 119219476RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.humanconcern.org",
        "donate_url": "https://www.humanconcern.org",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "idrf",
        "name": "International Development & Relief Foundation (IDRF)",
        "country": "CA",
        "description": "Development, relief, and local programs in Canada and internationally.",
        "registration_number": "BN 141815933RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.idrf.ca",
        "donate_url": "https://www.idrf.ca",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "nzf-canada",
        "name": "National Zakat Foundation Canada",
        "country": "CA",
        "description": "Dedicated to collecting and distributing Zakat locally to Muslims in Canada who are eligible recipients.",
        "registration_number": "BN 794660050RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.nzfcanada.com",
        "donate_url": "https://www.nzfcanada.com",
        "tags": ["Local Distribution"],
        "featured": False,
    },
    {
        "id": "canada-zakat",
        "name": "Canada Zakat (DawaNet)",
        "country": "CA",
        "description": "Local Zakat collection and distribution program under DawaNet, serving Canadian Muslim communities.",
        "registration_number": "BN 762916476RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.canadazakat.org",
        "donate_url": "https://www.canadazakat.org",
        "tags": ["Local Distribution"],
        "featured": False,
    },
    {
        "id": "icna-relief-canada",
        "name": "ICNA Relief Canada",
        "country": "CA",
        "description": "Social services and humanitarian relief, including food banks, refugee resettlement, and international programs.",
        "registration_number": "BN 836468698RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.icnareliefcanada.ca",
        "donate_url": "https://www.icnareliefcanada.ca",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "penny-appeal-canada",
        "name": "Penny Appeal Canada",
        "country": "CA",
        "description": "International humanitarian aid focused on poverty alleviation, emergency relief, and sustainable development.",
        "registration_number": "BN 812040996RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.pennyappeal.ca",
        "donate_url": "https://www.pennyappeal.ca",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "mac-foundation",
        "name": "Muslim Association of Canada (MAC) Foundation",
        "country": "CA",
        "description": "Community development, education support, and local outreach programs for Canadian Muslims.",
        "registration_number": "BN 897913344RR0001",
        "registration_label": "CRA Registered",
        "website": "https://www.macfoundation.ca",
        "donate_url": "https://www.macfoundation.ca",
        "tags": ["Local Distribution"],
        "featured": False,
    },

    # ── USA ──────────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-usa",
        "name": "Islamic Relief USA",
        "country": "US",
        "description": "One of the largest Muslim humanitarian organizations in the USA, providing international emergency relief and local programs.",
        "registration_number": "EIN 95-4453134",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.irusa.org",
        "donate_url": "https://www.irusa.org",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "zakat-foundation",
        "name": "Zakat Foundation of America",
        "country": "US",
        "description": "Emergency relief, education, and orphan sponsorship worldwide. Accepts and distributes Zakat in the USA and internationally.",
        "registration_number": "EIN 36-4476244",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.zakat.org",
        "donate_url": "https://www.zakat.org",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "hhrd",
        "name": "Helping Hand for Relief & Development (HHRD)",
        "country": "US",
        "description": "Disaster relief and sustainable development programs in over 30 countries.",
        "registration_number": "EIN 36-4582186",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.hhrd.org",
        "donate_url": "https://www.hhrd.org",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "icna-relief-usa",
        "name": "ICNA Relief USA",
        "country": "US",
        "description": "Domestic social services including food pantries, disaster relief, and refugee assistance, plus international programs.",
        "registration_number": "EIN 11-3231048",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.icnarelief.org",
        "donate_url": "https://www.icnarelief.org",
        "tags": ["International Relief", "Local Distribution"],
        "featured": False,
    },
    {
        "id": "united-muslim-relief",
        "name": "United Muslim Relief (UMR)",
        "country": "US",
        "description": "International humanitarian aid responding to crises and supporting long-term development.",
        "registration_number": "EIN 20-0800422",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.unitedmuslimrelief.org",
        "donate_url": "https://www.unitedmuslimrelief.org",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "penny-appeal-usa",
        "name": "Penny Appeal USA",
        "country": "US",
        "description": "Humanitarian aid focused on water, food, education, and emergency relief.",
        "registration_number": "EIN 47-3929655",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.pennyappealusa.org",
        "donate_url": "https://www.pennyappealusa.org",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "muslim-aid-usa",
        "name": "Muslim Aid USA",
        "country": "US",
        "description": "International relief and development, focusing on emergency response and long-term aid.",
        "registration_number": "EIN 82-2169123",
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.muslimaidusa.org",
        "donate_url": "https://www.muslimaidusa.org",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "embracing",
        "name": "Embracing",
        "country": "US",
        "description": "Mental health counseling and social services for Muslim communities across the USA. Focuses entirely on local needs.",
        "registration_number": None,
        "registration_label": "IRS 501(c)(3)",
        "website": "https://www.embracing.org",
        "donate_url": "https://www.embracing.org",
        "tags": ["Local Distribution"],
        "featured": False,
    },

    # ── UNITED KINGDOM ───────────────────────────────────────────────────────
    {
        "id": "islamic-relief-uk",
        "name": "Islamic Relief UK",
        "country": "GB",
        "description": "One of the world's leading Muslim charities, providing emergency relief and development programs in over 40 countries since 1984.",
        "registration_number": "Charity No. 328158",
        "registration_label": "Charity Commission (England & Wales)",
        "website": "https://www.islamic-relief.org.uk",
        "donate_url": "https://donate.islamic-relief.org.uk",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "national-zakat-foundation-uk",
        "name": "National Zakat Foundation",
        "country": "GB",
        "description": "Collects and locally distributes Zakat to eligible Muslims across the UK, helping them become self-sufficient.",
        "registration_number": "Charity No. 1153719",
        "registration_label": "Charity Commission (England & Wales)",
        "website": "https://nzf.org.uk",
        "donate_url": "https://nzf.org.uk/give/",
        "tags": ["Local Distribution"],
        "featured": False,
    },
    {
        "id": "penny-appeal-uk",
        "name": "Penny Appeal",
        "country": "GB",
        "description": "Award-winning UK charity transforming lives across Asia, Africa, and the Middle East through water, food, and education projects.",
        "registration_number": "Charity No. 1128341",
        "registration_label": "Charity Commission (England & Wales)",
        "website": "https://pennyappeal.org",
        "donate_url": "https://pennyappeal.org/appeal/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "muslim-aid-uk",
        "name": "Muslim Aid",
        "country": "GB",
        "description": "British Muslim charity delivering emergency relief, development programs, and community support worldwide since 1985.",
        "registration_number": "Charity No. 1176462",
        "registration_label": "Charity Commission (England & Wales)",
        "website": "https://www.muslimaid.org",
        "donate_url": "https://www.muslimaid.org/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "human-appeal-uk",
        "name": "Human Appeal",
        "country": "GB",
        "description": "Provides emergency relief and sustainable development projects focusing on the most vulnerable communities globally.",
        "registration_number": "Charity No. 1094904",
        "registration_label": "Charity Commission (England & Wales)",
        "website": "https://humanappeal.org.uk",
        "donate_url": "https://humanappeal.org.uk/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "ummah-welfare-trust",
        "name": "Ummah Welfare Trust",
        "country": "GB",
        "description": "British Muslim charity providing food, water, shelter, and education support to communities in need across many countries.",
        "registration_number": "Charity No. 1000851",
        "registration_label": "Charity Commission (England & Wales)",
        "website": "https://www.uwt.org",
        "donate_url": "https://www.uwt.org/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },

    # ── AUSTRALIA ────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-australia",
        "name": "Islamic Relief Australia",
        "country": "AU",
        "description": "Delivers emergency relief, sustainable development, and orphan sponsorship programs across the globe from Australia.",
        "registration_number": "ABN 49 070 827 462",
        "registration_label": "ACNC Registered",
        "website": "https://islamicrelief.com.au",
        "donate_url": "https://islamicrelief.com.au/donate/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "human-appeal-australia",
        "name": "Human Appeal Australia",
        "country": "AU",
        "description": "Delivers food, water, and emergency aid to communities across Asia, Africa and the Middle East from its Australian base.",
        "registration_number": None,
        "registration_label": "ACNC Registered",
        "website": "https://humanappeal.org.au",
        "donate_url": "https://humanappeal.org.au/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "penny-appeal-australia",
        "name": "Penny Appeal Australia",
        "country": "AU",
        "description": "Fighting poverty through small donations that make a big difference — water, food, orphan care, and emergency relief.",
        "registration_number": None,
        "registration_label": "ACNC Registered",
        "website": "https://pennyappeal.org.au",
        "donate_url": "https://pennyappeal.org.au/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "muslim-aid-australia",
        "name": "Muslim Aid Australia",
        "country": "AU",
        "description": "Provides aid to vulnerable communities regardless of religion, race, or nationality, with a focus on sustainable development.",
        "registration_number": None,
        "registration_label": "ACNC Registered",
        "website": "https://muslimaid.com.au",
        "donate_url": "https://muslimaid.com.au/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "zakat-foundation-australia",
        "name": "Zakat Foundation of Australia",
        "country": "AU",
        "description": "Collects and distributes Zakat within Australia and internationally, helping Muslims fulfill their obligation effectively.",
        "registration_number": None,
        "registration_label": "ACNC Registered",
        "website": "https://www.zakatfoundation.org.au",
        "donate_url": "https://www.zakatfoundation.org.au/donate/",
        "tags": ["Local Distribution"],
        "featured": False,
    },

    # ── SOUTH AFRICA ─────────────────────────────────────────────────────────
    {
        "id": "sanzaf",
        "name": "SANZAF — South African National Zakah Fund",
        "country": "ZA",
        "description": "South Africa's primary Zakat collecting and distributing body, empowering eligible recipients (mustahiqueen) since 1974.",
        "registration_number": None,
        "registration_label": "NPO Registered",
        "website": "https://www.sanzaf.org.za",
        "donate_url": "https://www.sanzaf.org.za/donate/",
        "tags": ["Local Distribution"],
        "featured": True,
    },
    {
        "id": "al-imdaad-foundation",
        "name": "Al Imdaad Foundation",
        "country": "ZA",
        "description": "South African Muslim charity providing food parcels, orphan care, and disaster relief to communities locally and abroad.",
        "registration_number": "NPO 020-938",
        "registration_label": "NPO Registered",
        "website": "https://www.alimdaad.com",
        "donate_url": "https://www.alimdaad.com/donate/",
        "tags": ["Local Distribution", "International Relief"],
        "featured": False,
    },
    {
        "id": "islamic-relief-south-africa",
        "name": "Islamic Relief South Africa",
        "country": "ZA",
        "description": "Humanitarian organization providing relief and development support to vulnerable communities in South Africa and across Africa.",
        "registration_number": None,
        "registration_label": "NPO Registered",
        "website": "https://islamicrelief.org.za",
        "donate_url": "https://islamicrelief.org.za/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "africa-muslim-agency",
        "name": "Africa Muslim Agency (AMA)",
        "country": "ZA",
        "description": "Delivers relief, development, and educational programs across Africa, serving Muslim and non-Muslim communities alike.",
        "registration_number": None,
        "registration_label": "NPO Registered",
        "website": "https://www.ama.org.za",
        "donate_url": "https://www.ama.org.za/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },

    # ── GERMANY ──────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-deutschland",
        "name": "Islamic Relief Deutschland",
        "country": "DE",
        "description": "German branch of Islamic Relief providing emergency aid and long-term development programs across more than 30 countries.",
        "registration_number": None,
        "registration_label": "Gemeinnütziger Verein (e.V.)",
        "website": "https://www.islamicrelief.de",
        "donate_url": "https://www.islamicrelief.de/spenden/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "muslim-helfen",
        "name": "Muslim Helfen",
        "country": "DE",
        "description": "Provides food aid, drinking water projects, and emergency assistance to impoverished communities in crisis regions.",
        "registration_number": None,
        "registration_label": "Gemeinnütziger Verein (e.V.)",
        "website": "https://muslimhelfen.org",
        "donate_url": "https://muslimhelfen.org/spenden/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "hilfswerk-islam",
        "name": "Hilfswerk Islam",
        "country": "DE",
        "description": "German Muslim charity supporting orphans, providing emergency relief, and funding education projects globally.",
        "registration_number": None,
        "registration_label": "Gemeinnütziger Verein (e.V.)",
        "website": "https://hilfswerk-islam.de",
        "donate_url": "https://hilfswerk-islam.de/spenden/",
        "tags": ["International Relief"],
        "featured": False,
    },

    # ── FRANCE ───────────────────────────────────────────────────────────────
    {
        "id": "secours-islamique-france",
        "name": "Secours Islamique France (SIF)",
        "country": "FR",
        "description": "French humanitarian organization providing emergency aid and sustainable development across 20+ countries since 1991.",
        "registration_number": None,
        "registration_label": "Association Reconnue d'Utilité Publique",
        "website": "https://www.secours-islamique.org",
        "donate_url": "https://www.secours-islamique.org/faire-un-don/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "islamic-relief-france",
        "name": "Islamic Relief France",
        "country": "FR",
        "description": "French branch of Islamic Relief delivering humanitarian assistance and development projects across four continents.",
        "registration_number": None,
        "registration_label": "Association Loi 1901",
        "website": "https://islamicrelief.fr",
        "donate_url": "https://islamicrelief.fr/faire-un-don/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "muslim-aid-france",
        "name": "Muslim Aid France",
        "country": "FR",
        "description": "Collects Zakat and Sadaqah from French Muslims and channels them to eligible recipients in France and internationally.",
        "registration_number": None,
        "registration_label": "Association Loi 1901",
        "website": "https://muslimaid.fr",
        "donate_url": "https://muslimaid.fr/faire-un-don/",
        "tags": ["Local Distribution", "International Relief"],
        "featured": False,
    },

    # ── NETHERLANDS ──────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-nederland",
        "name": "Islamic Relief Nederland",
        "country": "NL",
        "description": "Dutch branch of Islamic Relief supporting emergency relief and development programs across Asia and Africa.",
        "registration_number": None,
        "registration_label": "ANBI Recognized",
        "website": "https://www.islamicrelief.nl",
        "donate_url": "https://www.islamicrelief.nl/doneer/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "human-appeal-nederland",
        "name": "Human Appeal Nederland",
        "country": "NL",
        "description": "Netherlands-based humanitarian organization funding food, water, and medical assistance programs in crisis regions.",
        "registration_number": None,
        "registration_label": "ANBI Recognized",
        "website": "https://humanappeal.nl",
        "donate_url": "https://humanappeal.nl/doneer/",
        "tags": ["International Relief"],
        "featured": False,
    },

    # ── IRELAND ──────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-ireland",
        "name": "Islamic Relief Ireland",
        "country": "IE",
        "description": "Irish branch of Islamic Relief delivering humanitarian and development programs across the globe.",
        "registration_number": None,
        "registration_label": "Revenue Approved Charity (CHY)",
        "website": "https://islamicrelief.ie",
        "donate_url": "https://islamicrelief.ie/donate/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "muslim-sisters-eire",
        "name": "Muslim Sisters of Éire",
        "country": "IE",
        "description": "Empowers Muslim women and families in Ireland through community support, Zakat distribution, and social welfare programs.",
        "registration_number": None,
        "registration_label": "Revenue Approved Charity (CHY)",
        "website": "https://muslimsisters.ie",
        "donate_url": "https://muslimsisters.ie/donate/",
        "tags": ["Local Distribution"],
        "featured": False,
    },

    # ── SWEDEN ───────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-sverige",
        "name": "Islamic Relief Sverige",
        "country": "SE",
        "description": "Swedish branch of Islamic Relief funding international humanitarian projects from water wells to emergency food aid.",
        "registration_number": "Org. nr 802429-9882",
        "registration_label": "90-konto Godkänd",
        "website": "https://www.islamicrelief.se",
        "donate_url": "https://www.islamicrelief.se/ge/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "human-appeal-sverige",
        "name": "Human Appeal Sverige",
        "country": "SE",
        "description": "Swedish office of Human Appeal raising funds for emergency relief and sustainable development across crisis regions.",
        "registration_number": None,
        "registration_label": "Ideell Förening",
        "website": "https://humanappeal.se",
        "donate_url": "https://humanappeal.se/donera/",
        "tags": ["International Relief"],
        "featured": False,
    },

    # ── NORWAY ───────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-norge",
        "name": "Islamic Relief Norge",
        "country": "NO",
        "description": "Norwegian branch of Islamic Relief raising funds for international humanitarian assistance and development programs.",
        "registration_number": "Org. nr 987 128 388",
        "registration_label": "Frivillighetsregisteret",
        "website": "https://www.islamicrelief.no",
        "donate_url": "https://www.islamicrelief.no/gi/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "human-appeal-norge",
        "name": "Human Appeal Norge",
        "country": "NO",
        "description": "Norwegian office of Human Appeal providing emergency relief, food, and water programs to vulnerable communities globally.",
        "registration_number": None,
        "registration_label": "Frivillighetsregisteret",
        "website": "https://humanappeal.no",
        "donate_url": "https://humanappeal.no/gi/",
        "tags": ["International Relief"],
        "featured": False,
    },

    # ── NEW ZEALAND ──────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-nz",
        "name": "Islamic Relief New Zealand",
        "country": "NZ",
        "description": "New Zealand branch supporting Islamic Relief's global humanitarian work across water, food, and emergency relief programs.",
        "registration_number": None,
        "registration_label": "Charities Commission NZ",
        "website": "https://islamicrelief.org.nz",
        "donate_url": "https://islamicrelief.org.nz/donate/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "human-appeal-nz",
        "name": "Human Appeal New Zealand",
        "country": "NZ",
        "description": "NZ fundraising arm of Human Appeal delivering relief and development aid to crisis-affected communities worldwide.",
        "registration_number": None,
        "registration_label": "Charities Commission NZ",
        "website": "https://humanappeal.org.nz",
        "donate_url": "https://humanappeal.org.nz/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },

    # ── MALAYSIA ─────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-malaysia",
        "name": "Islamic Relief Malaysia",
        "country": "MY",
        "description": "Provides humanitarian aid and sustainable development support to vulnerable communities in Malaysia and internationally.",
        "registration_number": None,
        "registration_label": "ROS Registered",
        "website": "https://islamicrelief.my",
        "donate_url": "https://islamicrelief.my/donate/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "mercy-malaysia",
        "name": "MERCY Malaysia",
        "country": "MY",
        "description": "International humanitarian organization providing emergency medical and relief assistance globally since 1999.",
        "registration_number": None,
        "registration_label": "ROS Registered",
        "website": "https://mercy.org.my",
        "donate_url": "https://mercy.org.my/donate/",
        "tags": ["International Relief"],
        "featured": False,
    },
    {
        "id": "yayasan-hasanah",
        "name": "Yayasan Hasanah",
        "country": "MY",
        "description": "Malaysian foundation supporting education, economic empowerment, and community development for underprivileged Malaysians.",
        "registration_number": None,
        "registration_label": "ROS Registered",
        "website": "https://hasanah.my",
        "donate_url": "https://hasanah.my/donate/",
        "tags": ["Local Distribution"],
        "featured": False,
    },

    # ── BANGLADESH ───────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-bangladesh",
        "name": "Islamic Relief Bangladesh",
        "country": "BD",
        "description": "Providing disaster relief, livelihood support, and development programs to vulnerable communities across Bangladesh.",
        "registration_number": None,
        "registration_label": "NGO Affairs Bureau",
        "website": "https://islamicrelief.org.bd",
        "donate_url": "https://islamicrelief.org.bd/donate/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "manabik-shahajya-sangstha",
        "name": "Manabik Shahajya Sangstha (MSS)",
        "country": "BD",
        "description": "Bangladeshi development organization supporting marginalized communities through livelihood, health, and education programs.",
        "registration_number": None,
        "registration_label": "NGO Affairs Bureau",
        "website": "https://mssbd.org",
        "donate_url": "https://mssbd.org/donate/",
        "tags": ["Local Distribution"],
        "featured": False,
    },

    # ── PAKISTAN ─────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-pakistan",
        "name": "Islamic Relief Pakistan",
        "country": "PK",
        "description": "Operating since 1992, delivering food, water, shelter, and income-generation programs to Pakistan's most vulnerable people.",
        "registration_number": None,
        "registration_label": "SECP Registered",
        "website": "https://islamicrelief.org.pk",
        "donate_url": "https://islamicrelief.org.pk/donate/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "edhi-foundation",
        "name": "Edhi Foundation",
        "country": "PK",
        "description": "Pakistan's largest welfare organization providing free ambulance service, orphanages, homeless shelters, and rehabilitation since 1951.",
        "registration_number": None,
        "registration_label": "SECP Registered",
        "website": "https://edhi.org",
        "donate_url": "https://edhi.org/donate/",
        "tags": ["Local Distribution"],
        "featured": False,
    },

    # ── INDIA ────────────────────────────────────────────────────────────────
    {
        "id": "islamic-relief-india",
        "name": "Islamic Relief India",
        "country": "IN",
        "description": "Working to alleviate poverty and suffering in India through food security, livelihood programs, and emergency response.",
        "registration_number": None,
        "registration_label": "FCRA Registered",
        "website": "https://islamicreliefindia.org",
        "donate_url": "https://islamicreliefindia.org/donate/",
        "tags": ["International Relief", "Local Distribution"],
        "featured": True,
    },
    {
        "id": "helpinghand-india",
        "name": "Helping Hand Foundation India",
        "country": "IN",
        "description": "Indian Muslim NGO delivering education, healthcare, and relief programs to underprivileged communities nationwide.",
        "registration_number": None,
        "registration_label": "FCRA Registered",
        "website": "https://hhfindia.org",
        "donate_url": "https://hhfindia.org/donate/",
        "tags": ["Local Distribution"],
        "featured": False,
    },

    # ── TURKEY ───────────────────────────────────────────────────────────────
    {
        "id": "ihh-turkey",
        "name": "İHH İnsani Yardım Vakfı",
        "country": "TR",
        "description": "One of the world's largest Islamic humanitarian organizations, delivering aid to over 120 countries since 1992.",
        "registration_number": None,
        "registration_label": "Vakıflar Genel Müdürlüğü",
        "website": "https://www.ihh.org.tr",
        "donate_url": "https://www.ihh.org.tr/bagis/",
        "tags": ["International Relief"],
        "featured": True,
    },
    {
        "id": "deniz-feneri",
        "name": "Deniz Feneri Derneği",
        "country": "TR",
        "description": "Turkish charity providing social aid, food support, and international humanitarian assistance to those in need globally.",
        "registration_number": None,
        "registration_label": "İçişleri Bakanlığı Dernek",
        "website": "https://www.denizyeneri.org.tr",
        "donate_url": "https://www.denizyeneri.org.tr/bagis/",
        "tags": ["Local Distribution", "International Relief"],
        "featured": False,
    },
]

# Auto-generate country options from charity data in preferred order
def _build_country_options() -> list:
    countries_in_data = {c["country"] for c in CHARITIES}
    ordered = [code for code in _COUNTRY_ORDER if code in countries_in_data]
    # Append any remaining codes not in the preferred order
    for code in sorted(countries_in_data - set(ordered)):
        ordered.append(code)
    return [
        {"code": code, "label": _COUNTRY_NAMES.get(code, code), "flag": _flag(code)}
        for code in ordered
    ]


COUNTRY_OPTIONS = _build_country_options()
